# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# 
development:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
  host: localhost
  database: sns_app

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/lib/mysql/mysql.sock
  username: sns_app
  host: sns-app.cs7aojmjpnkl.ap-northeast-1.rds.amazonaws.com
  database: sns_app
  password: <%= ENV['RAILS_APP_DATABASE_PASSWORD'] %